import type { CondoAssociation, Filing } from "@/lib/types";

export const condoAssociations: CondoAssociation[] = [
  {
    id: "sunset-harbor",
    legalName: "Sunset Harbor Condominium Association, Inc.",
    city: "Miami",
    state: "FL",
    county: "Miami-Dade",
    zip: "33139",
    latitude: 25.7873,
    longitude: -80.1564,
    unitCount: 312,
    managerEmail: "manager@sunsetharbor.org",
    complianceStatus: "Compliant",
    nextDeadline: "2026-05-15",
    lastPublishedAt: "2026-01-20",
  },
  {
    id: "palm-terrace",
    legalName: "Palm Terrace Owners Association",
    city: "Fort Lauderdale",
    state: "FL",
    county: "Broward",
    zip: "33301",
    latitude: 26.1223,
    longitude: -80.1434,
    unitCount: 88,
    managerEmail: "hoa@palmterrace.com",
    complianceStatus: "At Risk",
    nextDeadline: "2026-03-10",
    lastPublishedAt: "2025-11-05",
  },
  {
    id: "oak-ridge-towers",
    legalName: "Oak Ridge Towers Condominium",
    city: "Tampa",
    state: "FL",
    county: "Hillsborough",
    zip: "33602",
    latitude: 27.9506,
    longitude: -82.4572,
    unitCount: 26,
    managerEmail: "admin@oakridgetowers.net",
    complianceStatus: "Overdue",
    nextDeadline: "2026-02-15",
    lastPublishedAt: "2025-07-01",
  },
  {
    id: "bayside-court",
    legalName: "Bayside Court Condominium Association",
    city: "Orlando",
    state: "FL",
    county: "Orange",
    zip: "32801",
    latitude: 28.5409,
    longitude: -81.3797,
    unitCount: 154,
    managerEmail: "ops@baysidecourt.us",
    complianceStatus: "Compliant",
    nextDeadline: "2026-04-01",
    lastPublishedAt: "2026-02-02",
  },
];

export const filings: Filing[] = [
  {
    id: "f1",
    condoId: "sunset-harbor",
    type: "Annual Budget",
    periodLabel: "FY 2026",
    publishedAt: "2026-01-20",
    sourceLabel: "Association Portal",
    sourceUrl: "https://example.org/sunset-harbor/budget-2026",
  },
  {
    id: "f2",
    condoId: "sunset-harbor",
    type: "Reserve Study",
    periodLabel: "2025 Update",
    publishedAt: "2025-12-15",
    sourceLabel: "Engineering Report",
    sourceUrl: "https://example.org/sunset-harbor/reserve-study-2025",
  },
  {
    id: "f3",
    condoId: "palm-terrace",
    type: "Year-End Financial Statement",
    periodLabel: "FY 2025",
    publishedAt: "2025-11-05",
    sourceLabel: "Accountant Upload",
    sourceUrl: "https://example.org/palm-terrace/financials-2025",
  },
  {
    id: "f4",
    condoId: "bayside-court",
    type: "Insurance Summary",
    periodLabel: "2026 Renewal",
    publishedAt: "2026-02-02",
    sourceLabel: "Carrier Letter",
    sourceUrl: "https://example.org/bayside-court/insurance-2026",
  },
  {
    id: "f5",
    condoId: "oak-ridge-towers",
    type: "Board Meeting Minutes",
    periodLabel: "July 2025",
    publishedAt: "2025-07-01",
    sourceLabel: "Meeting Packet",
    sourceUrl: "https://example.org/oak-ridge/minutes-2025-07",
  },
];
